spring:
  profiles:
    group:
      local: "localdb,common"
      server: "serverdb,common"
    active: local
logging:
  level:
    root: info

---

spring:
  config:
    activate:
      on-profile: common
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver

  mvc:
    path match:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  sql:
    init:
      encoding: UTF-8
      continue-on-error: true
      mode: always
server:
  port: '80'

---

spring:
  config:
    activate:
      on-profile: localdb
  datasource:
    username: root
    url: jdbc:mariadb://localhost:3306/lolduo
    password: 1234

---

spring:
  config:
    activate:
      on-profile: serverdb
  datasource:
    username: root
    url: jdbc:mariadb://lol-duo-mariadb.cswfqjzaqdu0.ap-northeast-2.rds.amazonaws.com:3306/lolduo
    password: fhfebdh1