ALTER table item convert to charset utf8;
ALTER table champion convert to charset utf8;
ALTER table item_full convert to charset utf8;
ALTER table perk_id convert to charset utf8;
ALTER table solo convert to charset utf8;
ALTER table spell convert to charset utf8;
insert into perk_id(id, img_url, name) values (5001, "perk-images/StatMods/StatModsHealthScalingIcon.png","체력 +15 ~ 140(레벨에 비례)");
insert into perk_id(id, img_url, name) values (5002, "perk-images/StatMods/StatModsArmorIcon.png","방어력 +6");
insert into perk_id(id, img_url, name) values (5003, "perk-images/StatMods/StatModsMagicResIcon.MagicResist_Fix.png", "마법저항력 +8");
insert into perk_id(id, img_url, name) values (5005, "perk-images/StatMods/StatModsAttackSpeedIcon.png", "공격속도 +10%");
insert into perk_id(id, img_url, name) values (5007, "perk-images/StatMods/StatModsCDRScalingIcon.png", "스킬 가속 +8");
insert into perk_id(id, img_url, name) values (5008, "perk-images/StatMods/StatModsAdaptiveForceIcon.png", "적응형 능력치 +9");