version: 0.0
os: linux
files:
  - source: /
    destination: /home/build/dev
permissions:
  - object: /home/build/dev
    pattern: "**"
    owner: root
    mode: 777
hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 300
      runas: root